"""del Movie user_uid key

Revision ID: 51da60cc69af
Revises: 489d64aae602
Create Date: 2026-05-27 14:02:10.608334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "51da60cc69af"
down_revision: Union[str, Sequence[str], None] = "489d64aae602"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("movies_user_id_fkey"), "movies", type_="foreignkey")
    op.drop_column("movies", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("movies_user_id_fkey"), "movies", "users", ["user_id"], ["uid"]
    )
    # ### end Alembic commands ###
