"""add password_hashd

Revision ID: 55c1fc54ed0b
Revises: 14d84f9a441c
Create Date: 2026-05-13 16:06:34.932003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55c1fc54ed0b'
down_revision: Union[str, Sequence[str], None] = '14d84f9a441c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hashd', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hashd')
    # ### end Alembic commands ###
