"""relate users to movies

Revision ID: 5a84385e6d84
Revises: 20e1fd68d847
Create Date: 2026-05-16 10:28:09.142664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5a84385e6d84"
down_revision: Union[str, Sequence[str], None] = "20e1fd68d847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "movies", "users", ["user_id"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movies", type_="foreignkey")
    op.drop_column("movies", "user_id")
    # ### end Alembic commands ###
