"""add email

Revision ID: e3693a4e0499
Revises: 55c1fc54ed0b
Create Date: 2026-05-13 16:49:04.975675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3693a4e0499'
down_revision: Union[str, Sequence[str], None] = '55c1fc54ed0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
